name: Pr checks
on:
  pull_request_target:
    types:
      - opened
  workflow_dispatch: null
jobs:
  run_pr_checks:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: library/package-lock.json
      - name: Install dependencies
        working-directory: ./library
        run: |
          npm i
      - name: Run tests
        id: run_tests
        working-directory: ./library
        continue-on-error: true
        run: |
          npm run test
      - name: Check formatting
        id: check_formatting
        working-directory: ./library
        continue-on-error: true
        run: |
          npm run format:check
      - name: Lint
        id: lint
        working-directory: ./library
        continue-on-error: true
        run: |
          npm run lint
      - name: Generate status message and error status
        id: generate_status
        run: |
          status_message=""
          error="false"

          if [ ${{ steps.run_tests.outcome }} = "success" ]; then
            status_message="✅ All tests passed"
          else
            status_message="❌ Some tests have failed"
            error="true"
          fi

          if [ ${{ steps.check_formatting.outcome }} = "success" ]; then
            status_message="${status_message}\n✅ All files correctly formatted"
          else
            status_message="${status_message}\n❌ Some files have formatting errors"
            error="true"
          fi

          if [ ${{ steps.lint.outcome }} = "success" ]; then
            status_message="${status_message}\n✅ All files obey eslint rules"
          else
            status_message="${status_message}\n❌ Some files dont obey eslint rules"
            error="true"
          fi

          echo "status_message=${status_message}" >> $GITHUB_OUTPUT
          echo "error=${error}" >> $GITHUB_OUTPUT
      - name: Comment pr
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.generate_status.outputs.status_message }}"
            })
      - name: Set exit code
        run: |
