name: Pr checks
on:
  pull_request_target:
    types:
      - opened
  workflow_dispatch: null
jobs:
  run_pr_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: library/package-lock.json
      - name: Run pr checks
        run: |
          cd library

          npm i

          npm run test
          npm run format:check
          npm run lint
