name: Publish package
on:
  workflow_dispatch: null
jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup github registry
        run: |
          touch ~/.npmrc
          echo "@felipesanchezsoberanis:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
      - name: Bundle and publish library
        working-directory: ./library
        run: |
          npm i
          npm run build:library
          npm publish
