name: Publish package
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Chekout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Login to github registry
        run: |
          echo -e "felipesanchezsoberanis\n${{ secrets.GITHUB_TOKEN }}" | npm login --registry https://npm.pkg.github.com/ --auth-type legacy
      - name: Bundle and publish library
        run: |
          cd library
          npm ci
          npm run build:library
          cp package.json dist
          cd dist
          mkdir dist
          ls -I dist -I package.json | xargs -I {} mv {} dist
          npm publish
